#ifndef _FREE_REGIONS_GRAPH_H_
#define _FREE_REGIONS_GRAPH_H_

#include <Eigen/Dense>
#include <vector>
#include <memory>

#include <decomp_ros_utils/data_ros_utils.h>

using NodeId = int;
using EdgeId = int;

struct GraphEdge{
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW

    EdgeId id = -1;
    NodeId from = -1;
    NodeId to = -1;

    // direction generated by the gap_extractor
    Eigen::Vector3d goal = Eigen::Vector3d::Zero();

    Polyhedron2D corridor_2d_;
    Polyhedron3D corridor_3d_;

    Eigen::Matrix2d R_2d_;
    Eigen::Matrix3d R_;

    Eigen::Vector3d replan_pos_;

    double cost = 0.0;
};

struct GraphNode {
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW

    // the position of the robot when planning process starts
    Eigen::Vector3d state_pos_;

    Polyhedron3D polys_;
    Polyhedron2D polys_2d_;

    // bool root = false;
    bool visited = false;

    // GraphNode *parent;
    // std::vector<GraphNode*> children;

    NodeId id = -1;
    NodeId parent_id_ = -1;
    std::vector<NodeId> children_ids;

    std::vector<EdgeId> edge_ids;
};

class FreeRegionsGraph {
    public:
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
    typedef std::unique_ptr<FreeRegionsGraph> Ptr;

    FreeRegionsGraph() {}
    ~FreeRegionsGraph() {}

    // ---- merge params ----
    double merge_radius_ = 0.8;  

    NodeId createNode();
    void setRootNode(Eigen::Vector3d start_pos);

    GraphNode* getNode(NodeId id);
    GraphNode* getRootNode() { return (root_id_ >= 0) ? getNode(root_id_) : nullptr; }

    EdgeId addEdge(NodeId from, NodeId to, const Eigen::Vector3d& dir);
    GraphEdge* getEdge(EdgeId id);
    NodeId root_id_ = -1;

    NodeId upsertNode(const Eigen::Vector3d& state_pos,
                  const Polyhedron3D& local_poly_3d);
    NodeId upsertNode(const Eigen::Vector2d& state_pos,
                  const Polyhedron2D& local_poly_2d);

    // GraphNode* getRootNode() { return root_; }
    // GraphNode* getParentNode(GraphNode* node) { return node->parent; }

    private:
    // GraphNode* root_;
    std::vector<std::unique_ptr<GraphNode>> nodes_;
    std::vector<std::unique_ptr<GraphEdge>> edges_;
};

#endif  // _FREE_REGIONS_GRAPH_H_